// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBri2e1lrPtIvV2lWmmJ0b2qBGwOKmxcOE',
    appId: '1:177920090403:web:d26ec67cacc5e9a7a7ac96',
    messagingSenderId: '177920090403',
    projectId: 'languagelearner-98431',
    authDomain: 'languagelearner-98431.firebaseapp.com',
    storageBucket: 'languagelearner-98431.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWRZEJ63LCZBglSSJKbaK3ge3dQ9zUKo0',
    appId: '1:177920090403:android:0103a80d3b95c8aca7ac96',
    messagingSenderId: '177920090403',
    projectId: 'languagelearner-98431',
    storageBucket: 'languagelearner-98431.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7mr9hpV5k3P2hcBQrB5wg8ZAGSuodeLQ',
    appId: '1:177920090403:ios:0e5481b01f7b8dd7a7ac96',
    messagingSenderId: '177920090403',
    projectId: 'languagelearner-98431',
    storageBucket: 'languagelearner-98431.appspot.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7mr9hpV5k3P2hcBQrB5wg8ZAGSuodeLQ',
    appId: '1:177920090403:ios:5e97c486b39d5247a7ac96',
    messagingSenderId: '177920090403',
    projectId: 'languagelearner-98431',
    storageBucket: 'languagelearner-98431.appspot.com',
    iosBundleId: 'com.example.app1.RunnerTests',
  );
}
